// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJ5T4PYIzMeC-7F7jaDufXLgIxyB4mc8',
    appId: '1:483952641868:web:d777c36e2a3b65e93e71e9',
    messagingSenderId: '483952641868',
    projectId: 'project-pm2-7224d',
    authDomain: 'project-pm2-7224d.firebaseapp.com',
    storageBucket: 'project-pm2-7224d.firebasestorage.app',
    measurementId: 'G-ZF2NE9NBST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgKGt_462uV-iDO7VvVZWsmNIn6tzieQ',
    appId: '1:483952641868:android:c49877465ae289733e71e9',
    messagingSenderId: '483952641868',
    projectId: 'project-pm2-7224d',
    storageBucket: 'project-pm2-7224d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeJ5T4PYIzMeC-7F7jaDufXLgIxyB4mc8',
    appId: '1:483952641868:web:ab2d5a8e32bde9f23e71e9',
    messagingSenderId: '483952641868',
    projectId: 'project-pm2-7224d',
    authDomain: 'project-pm2-7224d.firebaseapp.com',
    storageBucket: 'project-pm2-7224d.firebasestorage.app',
    measurementId: 'G-SZF93831Z3',
  );
}
